"""empty message

Revision ID: 78c28cb22e60
Revises: 407a34196c64
Create Date: 2022-04-03 04:30:38.170584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c28cb22e60'
down_revision = '407a34196c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('ref_id', sa.String(length=50), nullable=True))
    op.add_column('post', sa.Column('subpage', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'post', ['subpage', 'author'])
    op.create_foreign_key(None, 'post', 'subpage', ['subpage'], ['id'])
    op.drop_column('post', 'subbedUsers')
    op.drop_column('post', 'comment_count')
    op.drop_column('subpage', 'subbedUsers')
    op.add_column('user', sa.Column('avatar_url', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('rank', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['name'])
    op.drop_column('user', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'rank')
    op.drop_column('user', 'avatar_url')
    op.add_column('subpage', sa.Column('subbedUsers', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('post', sa.Column('comment_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('subbedUsers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_column('post', 'subpage')
    op.drop_column('comment', 'ref_id')
    # ### end Alembic commands ###
